name: Build Android

on:
  push:
    branches:
      - main

jobs:
  deploy_prod:
     runs-on: ubuntu-latest
     steps:
      - name: PROD Checkout code
        uses: actions/checkout@v4

      - name: PROD Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: PROD Install dependencies
        run: yarn install
  
      - name: PROD Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: PROD Build with Gradle
        working-directory: android
        run: ./gradlew build

      - name: PROD Decode keystore
        env:
          PROD_KEYSTORE_BASE64: ${{ secrets.PROD_KEYSTORE_BASE64 }}
        run: |
          echo "$PROD_KEYSTORE_BASE64" | base64 -d > my-upload-key.jks

      - name: PROD Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: PROD Build APK
        working-directory: android
        run: ./gradlew assembleRelease
        env:
          PROD_KEYSTORE_PASSWORD: ${{ secrets.PROD_KEYSTORE_PASSWORD }}
          PROD_KEY_ALIAS: ${{ secrets.PROD_KEY_ALIAS }}
          PROD_KEY_PASSWORD: ${{ secrets.PROD_KEY_PASSWORD }}

      - name: PROD Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: prod-signed-apk
          path: android/app/build/outputs/apk/release/prod/app-release.apk
            
  #QA Deployment             
  # deploy_qa:
     runs-on: ubuntu-latest
     steps:
      - name: QA Checkout code
        uses: actions/checkout@v4

      - name: QA Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: QA Install dependencies
        run: yarn install
  
      - name: QA Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: QA Build with Gradle
        working-directory: android
        run: ./gradlew build

      - name: QA Decode keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.QA_KEYSTORE_BASE64 }}
        run: |
          echo "$QA_KEYSTORE_BASE64" | base64 -d > my-upload-key.jks

      - name: QA Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: QA Build APK
        working-directory: android
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.QA_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.QA_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.QA_KEY_PASSWORD }}

      - name: QA Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: qa-signed-apk
          path: android/app/build/outputs/apk/release/qa/app-release.apk
  deploy:
    needs: [deploy_prod,deploy_qa]
    runs-on: ubuntu-latest
    steps:
      - name: Get prod build artifacts
        uses: actions/download-artifact@v4
        with:
          name: prod-signed-apk

      # - name: Get qa build artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: qa-signed-apk
      - name: Deploy code
        run: echo "...Deployed"
