name: Build Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install
  
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle
        working-directory: android
        run: ./gradlew build

      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        working-directory: android
        run: ./gradlew assembleDebug
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Apk
          path: android/app/build/outputs/apk/release/app-release.apk
            
      - name: Deploy code
        run: echo "...Deployed"

      # - name: Upload APK
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: app-debug
      #     path: android/app/build/outputs/apk/release/app-release.apk


      # - name: Setup Android SDK
      #   uses: android-actions/setup-android@v2.0.10